openapi: 3.0.1
info:
  title: '@jupiterone/graph-aquasec'
  description: A graph conversion tool for https://aquasec.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-aquasec
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-aquasec'
